name: Unit Tests

on:
  push:
    paths:
      - "go.mod"
      - "**.go"
    branches: [main]

  pull_request:
    paths:
      - "go.mod"
      - "**.go"
    branches: [main]

jobs:
  run-unit-tests:
    name: Run Tests
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Go 1.24
        uses: actions/setup-go@v6
        with:
          go-version: "^1.24"

      - name: Check Out Code
        uses: actions/checkout@v5

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Go Unit Tests
        run: go test ./...
